### ISSUE TITLE
Verify algebra in the optimal_stopping.tex notes

### ISSUE THREAD

**Issue by jlperla** [econtoolkit/continuous_time_methods#12]
You will see that this is a split file which takes the discretization of the operator as given.  Check the algebra against http://www.princeton.edu/~moll/HACTproject/option_simple.pdf and make sure that I added the slack variable correctly in my addition, as we may need to use that specification for some approaches.

**Comment by stevenzhangdx** [comment]
I checked this file against Moll's one and everything looks great. Only one typo that has been corrected.
