### ISSUE TITLE
Basic code for discretizing non-uniform grid

### ISSUE THREAD

**Issue by jlperla** [econtoolkit/continuous_time_methods#28]
@stevenzhangdx  I am starting on this, but have added you as an observer.  May hand over to you for testing/etc.

**Comment by jlperla** [comment]
This code was almost complete.  Take a look at the new `discretize_nonuniform_univariate_diffusion_test` file which has a few barebones tests.  I have it generating the matrices, but I didn't check the results to see if they accurately match anything calculated by hand.  Can you do that?  I would start by going through the `discretize_univariate_diffusion.m` file to see if they code matches the aglebra.  After, add in a few extra test cases for different drifts/etc to make sure that this works.

**Comment by stevenzhangdx** [comment]
Sure, I will manually check results later. I am getting busy in the following two days. Probably, I will do new tasks during this weekend. Is it okay for you?

**Comment by jlperla** [comment]
Perfect.  Thanks for the time update!

**Comment by jlperla** [comment]
@stevenzhangdx @sevhou  I am adding in Sev, who will work with you to track down the problems

**Comment by jlperla** [comment]
I think you guys verified this.

**Comment by sevhou** [comment]
yep we did
